language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: s2q4bpO+tQVMNR/GxQwZiMJ/7gXuMovFOp9SSOLBi36dDB2Uax5cEFclsa+LH0oSi33O+7GAsxJ7MBvmXnCZBUjFI0i+PrSUOv63foPHL6XZy0KmsNnVdrrERUi3qQTEnHERt5OjxobPSa9rvysPKK1qjUWrLiWdg0qiVIDSolvnxAhxAomcPNyTg15dYYiTxFsLcuxnbbM0XUk4RjLT1kLaaLouRWNq2kqT78oZ4MvxfrfwQYjRF/pjGWHgbIqk3dCor4KYJJp93NA4RKW+EpNunPOvBLcR4QOileE3jr5hk5Of6YZWjZoK8FBddcy2xPusMPVgGkpVYuqpKB9CQqRsfFYdbSzDqcfuPCp9lay2yCpJZCNxSFhqE52XgbJnkMxrL5jxz6GprMBbo6e8Lwj/E4skwtnZdZMp5SphISP3cIgbR5ol0ewIXDrTIsJ4eih6AAZIO/0nIHEoEFzSSbTCTpQJycD4PVAHH2zCYeEdeUEs4H2qOAsrDMbyCfQKLa3rn9theqAJQJr4LRqRihqTXRSzM845PCHK5CZthLC4UUdhM3ovBcLKFb22TIGYmD/2kLYimjKGJpYz1UYNzVZaXoJpYcHIKgcaqy+HBvtGLpNLNv8Cqcbl3GVidpHXWfkMwTCdpwLGgeIFIj5npru9SBMUd0geEBpoyT0Vkho=
  file:
    - 'mdast-util-heading-style.js'
    - 'mdast-util-heading-style.min.js'
  on:
    tags: true
