language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: v02cw4CnKrnYEcg/T+kRv6e/NJktN780zAApL5QmD8yxGqPGkfE5gnO7y4VASCnXJL93mAG6axUxUftaarYwRauuNGHfty9fxfo8KiifXCj9X+NnNYoVlVIOc5TtxyTbN6ajWbKWJ5iHfsek8rsIzRmJiVzjk2IJ1xphYBJaGHYcH1D4VRWm22VLUghOs6wVIph4ltZYwPS7408or1KcTLRs5Zykf+G0HSBBpzWy/g7VoK7tvSQTadK0ifDfAKLmrpjr5ulS/LWdEC/n63Uw53/dLS/fBtM5jliYiiSIls9kr3B4usHAfrpt1lEpJgDoV+/Ei+tTOXk4EObkz4iSCue/vdQ87NlBiCkqMIZ7eim0SBHvQtf0H5wj6kCOlO/qr19/RA6Gs6T1rnXYtNZnI2w1uxntS/sfOteeXltBey1isybINXoGUj9BbvQj6UEBk+E7JF0ljaWg/XtOlj/rdtaR42MiYm11OvHuy0jIgg3YgHkFLjchRGuWR/7Ka7NAAeY7Jn76YW2KT65d3GbW3wZwao3MEnG1L6h+v4ODKzGC8brz357rBs/me11q4Yf3mT4Zjb30ywpx3xt08Uaep0kX5ioAnRNUas/kvVU2NFYmeJCsrForr18XeRANo6iC/DVSbzXJnrKUUArC6f1Y4Ev7ma7CR1Ew29ULfDCA8o8=
  file:
    - "mdast-util-heading-style.js"
    - "mdast-util-heading-style.min.js"
  on:
    tags: true
    node: '9.0'
